[package]
name = "jdwp-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
colored = "2.1.0"
clap = { version = "4.5.23", features = ["derive"] }